Repository sesem4/Nelda, pull requests merged in 2023-05, with the labels that each got.

#77 bugfix/75/spriteFrameRate
  Common/src/main/java/dk/sdu/sesem4/common/data/EntityParts/MovingPart.java
  Common/src/test/java/dk/sdu/sesem4/common/data/EntityParts/MovingPartTest.java
Labels: bug

#76 Bugfix/74/flipped sprite rendering
  Common/src/main/java/dk/sdu/sesem4/common/data/rendering/SpriteData.java
  Common/src/main/java/dk/sdu/sesem4/common/data/resource/Resource.java
  Common/src/main/java/module-info.java
  Core/src/main/java/dk/sdu/sesem4/core/Game.java
Labels: bug

#80 #9 Added collision test in RectangleTest
  Common/src/test/java/dk/sdu/sesem4/common/data/math/RectangleTest.java
Labels: feature

#82 Bug/81/undoMovement null check
  Common/src/main/java/dk/sdu/sesem4/common/data/EntityParts/MovingPart.java
  Common/src/test/java/dk/sdu/sesem4/common/data/EntityParts/MovingPartTest.java
Labels: bug

#86 Bugfix/84/convert texture path to string
  Common/src/main/java/dk/sdu/sesem4/common/data/rendering/SpriteData.java
  Common/src/main/java/dk/sdu/sesem4/common/data/resource/Resource.java
  Common/src/test/java/dk/sdu/sesem4/common/data/rendering/SpriteDataTest.java
Labels: bug

#88 Feature/05/player input movement functionality
  Common/src/main/java/dk/sdu/sesem4/common/SPI/ControlSPI.java
  Common/src/main/java/dk/sdu/sesem4/common/SPI/MovementControllerSPI.java
  Common/src/main/java/dk/sdu/sesem4/common/data/controllerParts/ControlType.java
  Common/src/main/java/dk/sdu/sesem4/common/data/gamedata/GameData.java
  Common/src/main/java/module-info.java
  KeyboardControl/pom.xml
  KeyboardControl/src/main/java/dk/sdu/sesem4/keyboardcontrol/KeyBoardController.java
  KeyboardControl/src/main/java/dk/sdu/sesem4/keyboardcontrol/KeyBoardMovementController.java
  KeyboardControl/src/main/java/module-info.java
  KeyboardControl/src/test/java/dk/sdu/sesem4/keyboardcontrol/KeyBoardControllerTest.java
  docs/diagrams/SequenceDiagrams/PlayerMovement.puml
  pom.xml
Labels: feature

#93 Added a controller locator utility
  Common/src/main/java/dk/sdu/sesem4/common/util/ControllerLocator.java
Labels: feature

#109 Feature/66/enemy moblin
  EnemyMoblin/pom.xml
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/blue/BlueMoblin.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/blue/BlueMoblinPlugin.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/common/Moblin.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/common/MoblinPlugin.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/common/MoblinPostProcessor.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/common/MoblinProcessor.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/red/RedMoblin.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/red/RedMoblinPlugin.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/spawner/EnemySpawner.java
  EnemyMoblin/src/main/java/module-info.java
  EnemyMoblin/src/main/resources/blue0.png
  EnemyMoblin/src/main/resources/blue1.png
  EnemyMoblin/src/main/resources/blue2.png
  EnemyMoblin/src/main/resources/blue3.png
  EnemyMoblin/src/main/resources/red0.png
  EnemyMoblin/src/main/resources/red1.png
  EnemyMoblin/src/main/resources/red2.png
  EnemyMoblin/src/main/resources/red3.png
  pom.xml
Labels: feature

#111 feature/110/octorok_add_controltype
  EnemyOctorok/src/main/java/dk/sdu/sesem4/octorok/common/OctorokPlugin.java
Labels: feature

#124 feature/117/create combat data
  Common/src/main/java/dk/sdu/sesem4/common/data/EntityParts/CombatPart.java
  Common/src/main/java/dk/sdu/sesem4/common/data/combat/Weapon.java
  Common/src/main/java/dk/sdu/sesem4/common/data/combat/WeaponType.java
  Common/src/main/java/module-info.java
Labels: feature

#125 feature/118/create-combatControllLocator
  Common/src/main/java/dk/sdu/sesem4/common/SPI/CombatControllerSPI.java
  Common/src/main/java/dk/sdu/sesem4/common/util/CombatControllerLocator.java
  docs/diagrams/ClassDiagrams/combat.puml
Labels: feature

#129 Feature/114/weapon sword
  Common/src/main/java/dk/sdu/sesem4/common/data/EntityParts/CombatPart.java
  Common/src/main/java/dk/sdu/sesem4/common/util/CombatControllerLocator.java
  Player/src/main/java/dk/sdu/sesem4/player/PlayerPlugin.java
  Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
  Sword/src/main/java/dk/sdu/sesem4/sword/Sword.java
  Sword/src/main/java/module-info.java
  WeaponSword/pom.xml
  WeaponSword/src/main/java/dk/sdu/sesem4/sword/Sword.java
  WeaponSword/src/main/java/dk/sdu/sesem4/sword/SwordCombat.java
  WeaponSword/src/main/java/dk/sdu/sesem4/sword/SwordCombatController.java
  WeaponSword/src/main/java/dk/sdu/sesem4/sword/SwordPlugin.java
  WeaponSword/src/main/java/module-info.java
  WeaponSword/src/main/resources/sword1.png
  WeaponSword/src/main/resources/sword2.png
  docs/diagrams/ClassDiagrams/combat.puml
  docs/diagrams/Event/eventClassDiagram.puml
  docs/diagrams/Event/sequenceDiagram.puml
  docs/diagrams/components.drawio
  pom.xml
Labels: feature

#130 Bugfix / 121 / Implement UUID in sprites
  Common/src/main/java/dk/sdu/sesem4/common/data/EntityParts/SpritePart.java
  Common/src/main/java/dk/sdu/sesem4/common/data/rendering/SpriteData.java
  Common/src/test/java/dk/sdu/sesem4/common/data/rendering/SpriteDataTest.java
  Core/src/main/java/dk/sdu/sesem4/core/Game.java
Labels: bug

#133 Feature / 73 / Simple AI
  Common/src/main/java/dk/sdu/sesem4/common/data/math/Vector2.java
  EnemyMoblin/src/main/java/dk/sdu/sesem4/moblin/common/MoblinPlugin.java
  EnemyOctorok/src/main/java/dk/sdu/sesem4/octorok/common/OctorokPlugin.java
  Map/src/main/java/dk/sdu/sesem4/map/MapUtil.java
  SimpleAI/pom.xml
  SimpleAI/src/main/java/dk/sdu/sesem4/SimpleAIMovement/SimpleAIMovement.java
  SimpleAI/src/main/java/dk/sdu/sesem4/SimpleAIMovement/SimpleAiMovementController.java
  SimpleAI/src/main/java/module-info.java
  SimpleAI/src/test/java/dk/sdu/sesem4/SimpleAIMovement/SimpleAIMovementTest.java
  SimpleAI/src/test/java/dk/sdu/sesem4/SimpleAIMovement/SimpleAiMovementControllerTest.java
  docs/diagrams/ClassDiagrams/combat.puml
  pom.xml
Labels: feature

#137 Testing / PlayerProcessing
  Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
  Player/src/test/java/dk/sdu/sesem4/player/PlayerProcessingServiceTest.java
Labels: Test

#138 Testing / Combat Part
  Common/pom.xml
  Common/src/test/java/dk/sdu/sesem4/common/data/EntityParts/CombatPartTest.java
Labels: Test

#134 Bugfix/123/make boundarybox smaller for all entities
  Map/src/main/java/dk/sdu/sesem4/map/MapPostProcessingService.java
  Map/src/main/java/dk/sdu/sesem4/map/MapUtil.java
  Map/src/test/java/dk/sdu/sesem4/map/MapPostProcessingServiceTest.java
  Map/src/test/java/dk/sdu/sesem4/map/MapUtilTest.java
Labels: bug

#136 Testing / Moving part
  Common/pom.xml
  Common/src/test/java/dk/sdu/sesem4/common/data/EntityParts/MovingPartTest.java
Labels: Test
